# Generated by Django 2.2.14 on 2020-07-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_survey.block_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='BlockMarkdown',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Block')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.block',),
        ),
        migrations.CreateModel(
            name='BlockRadioGroup',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Block')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.block',),
        ),
        migrations.CreateModel(
            name='SurveyStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='BlockRadioButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('radio_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='survey_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyStep'),
        ),
    ]
